// <auto-generated />
namespace Consultancy.Project.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class UniversityTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UniversityTable));
        
        string IMigrationMetadata.Id
        {
            get { return "201602142041002_UniversityTable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
